version: '3.8'

services:
  minio:
    image: "minio/minio:${MINIO_VERSION:-RELEASE.2025-04-22T22-12-26Z}"
    command: server /data --console-address ":9009"
    restart: unless-stopped
    ports:
      - "9000:9000"      # S3-API
      - "9009:9009"      # Web-консоль MinIO
    environment:
      MINIO_ROOT_USER:     ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - ./minio-data:/data
    networks: [appnet]

  db:
    image: pgautoupgrade/pgautoupgrade:13-alpine
    hostname: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: [appnet]

  app:
    image: heartexlabs/label-studio:latest   
    restart: unless-stopped
    depends_on: [db]
    ports:
      - "8080:8000"     
    environment:
      DJANGO_DB: default
      POSTGRE_NAME:     postgres
      POSTGRE_USER:     postgres
      POSTGRE_PASSWORD: ""
      POSTGRE_PORT:     5432
      POSTGRE_HOST:     db
      LABEL_STUDIO_HOST: ${LABEL_STUDIO_HOST:-}
      JSON_LOG: "1"
    volumes:
      - ./mydata:/label-studio/data
    command: label-studio-uwsgi
    networks: [appnet]

networks:
  appnet:
